sudo: required

services:
  - docker

language: r

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make build

deploy:
  - provider: script
    script:
        - make push
    on:
      branch: master
