apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mrr-forecaster
spec:
  schedule: "50 10 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mrr-forecaster
            image: bufferapp/mrr-forecaster:0.1.0
            env:
              - name: REDSHIFT_DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: database
              - name: REDSHIFT_USER
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: user
              - name: REDSHIFT_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: endpoint
              - name: REDSHIFT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: password
              - name: REDSHIFT_DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: port
              - name: LOOKER_API3_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: looker
                    key: client-id
              - name: LOOKER_API3_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: looker
                    key: client-secret
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                      name: aws
                      key: access-key-id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                      name: aws
                      key: secret-access-key
              - name: AWS_DEFAULT_REGION
                valueFrom:
                  secretKeyRef:
                      name: aws
                      key: default-region
          imagePullSecrets:
            - name: dockerhub
          restartPolicy: OnFailure
