apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: mrr-forecaster
spec:
  schedule: "0 15 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mrr-forecaster
            image: julheimer/mrr_forecaster:0.1.0
            env:
              - name: REDSHIFT_DB_NAME
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: database
              - name: REDSHIFT_USER
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: user
              - name: REDSHIFT_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: endpoint
              - name: REDSHIFT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: password
              - name: REDSHIFT_DB_PORT
                valueFrom:
                  secretKeyRef:
                    name: redshift
                    key: port
              - name: LOOKER_API3_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: looker
                    key: client-id
              - name: LOOKER_API3_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: looker
                    key: client-secret
            imagePullPolicy: Always
          restartPolicy: OnFailure
